name: install_ubuntu_deps
runs:
  using: composite
  steps:
  - name: install cmake
    # OpenEXR requires CMake 3.12. We also download CMake 3.20, which
    # we'll use later for the JS build only.
    run: |
      echo $(date +%F) > ./date
      echo $(git ls-remote https://github.com/facebookresearch/habitat-lab.git HEAD | awk '{ print $1}') > ./hablab_sha
      cat ./hablab_sha
      wget https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh
      sudo mkdir /opt/cmake312
      sudo sh ./cmake-3.12.4-Linux-x86_64.sh --prefix=/opt/cmake312 --skip-license
      sudo ln -s /opt/cmake312/bin/cmake /usr/local/bin/cmake
      sudo ln -s /opt/cmake312/bin/ctest /usr/local/bin/ctest
    shell: bash
  - name: Install dependencies
    run: |-
      echo "Install dependencies"
      sudo apt-get update || true
      sudo apt-get install -y --no-install-recommends \
        build-essential \
        git \
        git-lfs \
        curl \
        vim \
        ca-certificates \
        libjpeg-dev \
        libglm-dev \
        libegl1-mesa-dev \
        ninja-build \
        xorg-dev \
        freeglut3-dev \
        pkg-config \
        wget \
        zip \
        lcov\
        libhdf5-dev \
        libomp-dev \
        unzip || true
    shell: bash
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      miniconda-version: "latest"
      python-version: "3.9"
      activate-environment: "habitat"
  - name: Install conda and dependencies
    run: |-
      echo "Install conda and dependencies"
      # Pin NumPy 1.x globally to prevent any package from upgrading to 2.x
      # PyTorch 1.12.1 has ABI compatibility issues with NumPy 2.x (missing iJIT_NotifyEvent symbol)
      echo "numpy<2.0" >> $CONDA_PREFIX/conda-meta/pinned
      # PyTorch 1.12.1 is pinned for CUDA 11.3 compatibility with habitat-sim
      # Install with NumPy<2 constraint to ensure correct version
      conda install -y pytorch==1.12.1 torchvision==0.13.1 "numpy<2.0" -c pytorch -c nvidia
      conda install -y -c conda-forge ninja pytest pytest-cov ccache hypothesis pytest-mock
      # Pin opencv-python to version compatible with NumPy 1.x (opencv 4.10.0.84 is last before NumPy 2.x requirement)
      # PyTorch 1.12.1 requires NumPy 1.x for proper symbol resolution (iJIT_NotifyEvent)
      pip install pytest-sugar pytest-xdist pytest-benchmark "opencv-python<4.11" cython mock
    shell: bash -el {0}
  - name: Validate Pytorch Installation
    run: |-
      echo "Validate Pytorch Installation"
      # Check that pytorch is installed with CUDA.
      python -c 'import torch; torch.cuda.set_device(0)'
    shell: bash -el {0}
