name: install_ubuntu_deps
runs:
  using: composite
  steps:
  - name: Install dependencies
    run: |-
      echo "Install dependencies"
      sudo apt-get update || true
      sudo apt-get install -y --no-install-recommends \
        cmake \
        build-essential \
        git \
        git-lfs \
        curl \
        vim \
        ca-certificates \
        libjpeg-dev \
        libglm-dev \
        libegl1-mesa-dev \
        ninja-build \
        xorg-dev \
        freeglut3-dev \
        pkg-config \
        wget \
        zip \
        lcov\
        libhdf5-dev \
        libomp-dev \
        unzip || true
    shell: bash
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      miniconda-version: "latest"
      python-version: "3.9"
      activate-environment: "habitat"
  - name: Install conda and dependencies
    run: |-
      echo "Install conda and dependencies"
      conda install -y pytorch==1.12.1 torchvision==0.13.1 -c pytorch -c nvidia
      conda install -y -c conda-forge ninja numpy=1.26.4 pytest pytest-cov ccache hypothesis pytest-mock
      pip install pytest-sugar pytest-xdist pytest-benchmark opencv-python cython mock
    shell: bash -el {0}
  - name: Validate Pytorch Installation
    run: |-
      echo "Validate Pytorch Installation"
      # Check that pytorch is installed with CUDA.
      python -c 'import torch; torch.cuda.set_device(0)'
    shell: bash -el {0}
