# This action installs required Ubuntu NVIDIA dependencies.
# It assumes that `nvidia-smi` is available on the system.
name: "Install GPU Dependencies"
runs:
  using: composite
  steps:
  - name: Install GPU Dependencies
    shell: bash
    run: |
      NVIDIA_SMI_OUTPUT=$(nvidia-smi)
      # Extract CUDA version (e.g., 11.7)
      CUDA_VERSION=$(echo "$NVIDIA_SMI_OUTPUT" | grep -oP 'CUDA Version:\s+\K[\d.]+')

      MAJOR_DRIVER_VERSION=$(echo "$NVIDIA_SMI_OUTPUT" | grep -oP 'Driver Version:\s+\K\d+')
      sudo apt-get update
      sudo apt-get install -y cuda-toolkit-${CUDA_VERSION}
      sudo apt-get install -y nvidia-gds-${CUDA_VERSION}
      # Install all nvidia packages together so apt can resolve dependencies correctly.
      # Use the major driver version without pinning to a specific patch version,
      # allowing apt to select compatible versions across all packages.
      # Include EGL packages required for headless rendering with CUDA device matching.
      sudo apt-get install -y --allow-downgrades \
        libnvidia-common-${MAJOR_DRIVER_VERSION} \
        libnvidia-gl-${MAJOR_DRIVER_VERSION} \
        libnvidia-compute-${MAJOR_DRIVER_VERSION} \
        libnvidia-decode-${MAJOR_DRIVER_VERSION} \
        libnvidia-encode-${MAJOR_DRIVER_VERSION} \
        libnvidia-egl-wayland1 \
        libnvidia-cfg1-${MAJOR_DRIVER_VERSION}
  - name: Configure EGL for NVIDIA
    shell: bash
    run: |
      # Remove Mesa EGL vendor configuration to ensure NVIDIA EGL is used
      # Mesa's software renderer doesn't support CUDA device matching
      sudo rm -f /usr/share/glvnd/egl_vendor.d/50_mesa.json

      # Ensure NVIDIA EGL ICD is properly configured for headless rendering
      sudo mkdir -p /usr/share/glvnd/egl_vendor.d
      echo '{"file_format_version" : "1.0.0", "ICD" : {"library_path" : "libEGL_nvidia.so.0"}}' | sudo tee /usr/share/glvnd/egl_vendor.d/10_nvidia.json

      # Debug: List available EGL devices
      echo "=== EGL Debug Info ==="
      ls -la /usr/share/glvnd/egl_vendor.d/ || true
      cat /usr/share/glvnd/egl_vendor.d/*.json 2>/dev/null || true

      # Check for nvidia EGL libraries
      ldconfig -p | grep -i egl || true
      ldconfig -p | grep -i nvidia || true

      # Verify nvidia-smi can see the GPU
      echo "=== GPU Info ==="
      nvidia-smi -L || true
