# This action installs required Ubuntu NVIDIA dependencies.
# It assumes that `nvidia-smi` is available on the system.
name: "Install GPU Dependencies"
runs:
  using: composite
  steps:
  - name: Install GPU Dependencies
    shell: bash
    run: |
      NVIDIA_SMI_OUTPUT=$(nvidia-smi)
      # Extract CUDA version (e.g., 11.7)
      CUDA_VERSION=$(echo "$NVIDIA_SMI_OUTPUT" | grep -oP 'CUDA Version:\s+\K[\d.]+')

      MAJOR_DRIVER_VERSION=$(echo "$NVIDIA_SMI_OUTPUT" | grep -oP 'Driver Version:\s+\K\d+')
      sudo apt-get update
      sudo apt-get install -y cuda-toolkit-${CUDA_VERSION}
      sudo apt-get install -y nvidia-gds-${CUDA_VERSION}
      # Install all nvidia packages together so apt can resolve dependencies correctly.
      # Use the major driver version without pinning to a specific patch version,
      # allowing apt to select compatible versions across all packages.
      sudo apt-get install -y --allow-downgrades \
        libnvidia-common-${MAJOR_DRIVER_VERSION} \
        libnvidia-gl-${MAJOR_DRIVER_VERSION} \
        libnvidia-compute-${MAJOR_DRIVER_VERSION} \
        libnvidia-decode-${MAJOR_DRIVER_VERSION} \
        libnvidia-encode-${MAJOR_DRIVER_VERSION}
